pi-dashboard/pi_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "RPi Router Admin Login"
admin.site.site_title = "RPi Administration"
admin.site.index_title = "RPi Router"

urlpatterns = [
    path('', include('status.urls')),
    path('admin/', admin.site.urls),
]

pi-dashboard/status/urls.py
from django.urls import path

from . import views


app_name = 'status'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.dashboard, name='dashboard'),
    path('hotspot/', views.hotspot, name='hotspot'),
    path('interfaces/', views.interfaces, name='interfaces'),
    path('dhcp_dns/', views.dhcp_dns, name='dhcp_dns'),
    path('system/', views.system, name='system'),
    # path('authentication/', views.authentication, name='authentication'),
    path('about/', views.about, name='about')
]

pi-dashboard/status/models.py
from django.db import models


class Device_Data(models.Model):
    hostname = models.CharField(max_length=100)
    ip4_address = models.CharField(max_length=15)
    ip6_address = models.CharField(max_length=39)
    mac_address = models.CharField(max_length=17)
    bandw_in = models.IntegerField(default=0)
    bandw_out = models.IntegerField(default=0)
    bandw_total = models.IntegerField(default=0)
    last_seen = models.CharField(max_length=40)

pi-dashboard/status/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
import os
import re

hostap_status = os.popen('pidof hostapd | wc -l').readline()
cpu_temp = os.popen('vcgencmd measure_temp').readline()
mem_free = os.popen("free -m | awk '/Mem:/ {total=$2; used=$3} END { print used/total*100}'").readline()
rx_packets = os.popen('cat /sys/class/net/wlan0/statistics/rx_packets').readline()
tx_packets = os.popen('cat /sys/class/net/wlan0/statistics/tx_packets').readline()
tx_bytes = os.popen('cat /sys/class/net/wlan0/statistics/tx_bytes').readline()
rx_bytes = os.popen('cat /sys/class/net/wlan0/statistics/rx_bytes').readline()
iw_wlan0 = os.popen('iw dev wlan0 info').readlines()
devices = os.popen('cat /var/lib/misc/dnsmasq.leases').readlines()

system_infos = [
        {
            'hostapStatus': hostap_status,
            'cpuTemp': cpu_temp,
            'memFree': mem_free,
            'rxPackets': rx_packets,
            'txPackets': tx_packets,
            'txBytes': tx_bytes,
            'rxBytes': rx_bytes,
            'nicInfo': iw_wlan0,
            'connectedDevices': devices
        }
]

wifiStandards = {
        'a': '802.11a - 5 GHz',
        'b': '802.11b - 2.4 GHz',
        'g': '802.11g - 2.4 GHz',
        'n': '802.11n - 2.4 GHz',
        'ac': '802.11.ac - 5 GHz'
        }

def index(request):
    interfacesList = [x.strip() for x in os.popen('ls /sys/class/net').readlines()]
    ifconfigOut = os.popen('ifconfig').readlines()
    tmpInterface = ""
    interfacesStrs = []
    for interface in ifconfigOut:
        if interface == '\n':
            interfacesStrs.append(tmpInterface)
            tmpInterface = ""
        else:
            tmpInterface += interface

    zipInterfaces = zip(interfacesList,interfacesStrs)

    context = {
        'systemInfos': system_infos,
        'interfacesList': interfacesList,
        'zipInterfaces': zipInterfaces
    }
    return render(request, 'status/index.html',context)

def dashboard(request):
    devices = os.popen('arp -a').readlines()
    devicesLL = []
    i = 0

    for device in devices:
        deviceInfo = device.split(" ")
        if deviceInfo[0] != '?' and deviceInfo[3] != '<incomplete>' and deviceInfo[1] != '(1.1.1.1)':
            devicesLL.append({})
            devicesLL[i]["hostname"] = deviceInfo[0]
            devicesLL[i]["ip"] = deviceInfo[1][1:-1]
            devicesLL[i]["mac"] = deviceInfo[3].strip()
            i += 1
    context = {
        "devices": devicesLL
    }
    # os.system("sudo vnstat -u -i wlan0")
    os.system("rm status/static/status/img/summary1.png")
    os.system("rm status/static/status/img/summary3.png")
    os.system("vnstati -vs -c 1 -i wlan0 -o status/static/status/img/summary1.png")
    os.system("vnstati -s -i wlan0+eth0 -o status/static/status/img/summary3.png")

    return render(request, 'status/dashboard.html', context)

def hotspot(request):

    hostapdConf = [x.strip() for x in os.popen('cat /etc/hostapd/hostapd.conf').readlines()]

    ap_interface=""
    ap_ssid = ""
    ap_country_code = ""
    ap_channel = ""
    ap_passphrase = ""
    ap_hw_mode = ""

    for hostapdCon in hostapdConf:
        if (re.search('(?<=^interface=).*', hostapdCon)):
            ap_interface = re.search('(?<=^interface=).*', hostapdCon).group()
        if (re.search('(?<=^ssid=).*', hostapdCon)):
            ap_ssid = re.search('(?<=^ssid=).*', hostapdCon).group()
        if (re.search('(?<=^country_code=).*', hostapdCon)):
            ap_country_code = re.search('(?<=^country_code=).*', hostapdCon).group()
        if (re.search('(?<=^channel=).*', hostapdCon)):
            ap_channel = re.search('(?<=^channel=).*', hostapdCon).group()
        if (re.search('(?<=^wpa_passphrase=).*', hostapdCon)):
            ap_passphrase = re.search('(?<=^wpa_passphrase=).*', hostapdCon).group()
        if (re.search('(?<=^hw_mode=).*', hostapdCon)):
            ap_hw_mode = re.search('(?<=^hw_mode=).*', hostapdCon).group()

    context = {
        'apInterface': ap_interface,
        'apSSID': ap_ssid,
        'apChannel': ap_channel,
        'apPassphrase': ap_passphrase,
        'apHwMode': wifiStandards[ap_hw_mode],
        'apCountryCode': "US"
    }
    return render(request, 'status/hotspot.html',context)

def interfaces(request):
    interfacesList = [x.strip() for x in os.popen('ls /sys/class/net').readlines()]
    ifconfigOut = os.popen('ifconfig').readlines()
    tmpInterface = ""
    interfacesStrs = []
    for interface in ifconfigOut:
        if interface == '\n':
            interfacesStrs.append(tmpInterface)
            tmpInterface = ""
        else:
            tmpInterface += interface

    zipInterfaces = zip(interfacesList,interfacesStrs)

    context = {
        'systemInfos': system_infos,
        'interfacesList': interfacesList,
        'zipInterfaces': zipInterfaces
    }
    return render(request, 'status/interfaces.html', context)

def dhcp_dns(request):

    dnsmasqConf = [x.strip() for x in os.popen('cat /etc/dnsmasq.conf').readlines()]
    leases = [x.strip() for x in os.popen('cat /var/lib/misc/dnsmasq.leases').readlines()]

    interface = ""
    dhcp_range = ""
    start_ip = ""
    last_ip = ""
    lease_time = ""
    dns_server1 = ""

    for line in dnsmasqConf:
        if (re.search('(?<=^interface=).*', line)):
            interface = re.search('(?<=^interface=).*', line).group()
        if (re.search('(?<=^server=).*', line)):
            dns_server1 = re.search('(?<=^server=).*',line).group()
        if (re.search('(?<=^dhcp-range=).*', line)):
            dhcp_range = re.search('(?<=^dhcp-range=).*',line).group()

    start_ip = dhcp_range.split(",")[0]
    last_ip = dhcp_range.split(",")[1]
    lease_time = dhcp_range.split(",")[2]
    clients = []

    for i,lease in zip(range(0,len(leases)),leases):
        clients.append({})
        clients[i]["hostname"] = lease.split(" ")[3]
        clients[i]["clientIP"] = lease.split(" ")[2]
        clients[i]["clientMAC"] = lease.split(" ")[1]
        clients[i]["clientID"] = lease.split(" ")[4]
        clients[i]["expireTime"] = lease.split(" ")[0]

    context = {
        'interface': interface,
        'startAddress': start_ip,
        'lastAddress': last_ip,
        'leaseTime': lease_time,
        'dnsServer': dns_server1,
        'clients': clients
    }

    return render(request, 'status/dhcp_dns.html', context)


# def authentication(request):
#     return render(request, 'status/system.html')

def system(request):
    return render(request, 'status/system.html')

def about(request):
    return render(request, 'status/about.html')

pi-dashboard/status/templates/status/about.html
{% extends "status/base.html" %}
{% block content %}
		<!-- <p>This website is created for the Raspberry Pi router.</p>
		<p>It is still in developement</p> -->
		<div class="container">
			<div class="row">
				<div class>
					Creator: Jonathan Saenz<br>
					Inspiration: Wanted to learn more about networking and my apartments don't have any secure access points to use<br>
					References: There are many guides online that I used as references and used <br>raspap application as a reference to build
					myapplication using Django web framework
				</div>
			</div>
		</div>
{% endblock content %}

pi-dashboard/status/templates/status/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- About meta tags -->
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'status/css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'status/css/sidebar.css' %}">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="shortcut icon" href="#">

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'status/css/sidebar.css' %}">

  {% if title %}
    <title>Pi-N-Route | {{ title }}</title>
  {% else %}
    <title>Pi-N-Route</title>
  {% endif %}

  </head>
  <body>
    <style>
    </style>


  <div class="d-flex toggled" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right d-none d-md-block" id="sidebar-wrapper">
      <div class="sidebar-heading">Pi-N-Route</div>
      <div class="list-group list-group-flush">
        <a href="{% url 'status:dashboard' %}" class="list-group-item list-group-item-action bg-light">Dashboard</a>
        <a href="{% url 'status:hotspot' %}" class="list-group-item list-group-item-action bg-light">Hotspot</a>
        <a href="{% url 'status:interfaces' %}" class="list-group-item list-group-item-action bg-light">Network Interfaces</a>
        <a href="{% url 'status:dhcp_dns' %}" class="list-group-item list-group-item-action bg-light">DHCP and DNS</a>
        <!-- <a href="{# url 'status:system' #}" class="list-group-item list-group-item-action bg-light">System</a> -->
        <!-- <a href="{# url 'status:authentication' #}" class="list-group-item list-group-item-action bg-light">Authentication</a> -->
        <a href="{% url 'status:about' %}" class="list-group-item list-group-item-action bg-light">About</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <button class="btn-circle btn-lg d-none d-md-block ml-1" id="menu-toggle"><i id="arrow" class="fa fa-arrow-left" aria-hidden="true"></i></button>

      <!--Navbar-->
      <nav class="navbar navbar-light purple lighten-4 mb-4 d-none d-block d-md-none">

        <div></div>

        <!-- Collapse button -->
        <button class="navbar-toggler toggler-example purple darken-3" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent41" aria-controls="navbarSupportedContent41" aria-expanded="false"
          aria-label="Toggle navigation"><span class="white-text"><i class="fa fa-bars"></i></span></button>

          <!-- Collapsible content -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent41">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a href="{% url 'status:dashboard' %}" class="nav-link">Dashboard</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'status:hotspot' %}" class="nav-link">Hotspot</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'status:interfaces' %}" class="nav-link">Network Interfaces</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'status:dhcp_dns' %}" class="nav-link">DHCP and DNS</a>
              </li>
              <!-- <li class="nav-item">
                <a href="{# url 'status:system' #}" class="nav-link">System</a>
              </li> -->
              <!-- <li class="nav-item">
                <a href="#" class="nav-link">Authentication</a>
              </li> -->
              <li class="nav-item">
                <a href="{% url 'status:about' %}" class="nav-link">About</a>
              </li>
            </ul>
            <!-- Links -->
          </div>
          <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->
      {% block content %}{% endblock %}
    </div>
    <!-- /#page-content-wrapper -->
  </div>
  <!-- /#wrapper -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#arrow").toggleClass("fa-arrow-right fa-arrow-left")
        $("#wrapper").toggleClass("toggled");
      });
    </script>
  </body>
</html>

pi-dashboard/status/templates/status/dashboard.html
{% extends "status/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col">Dashboard</div>
						<div class="col text-right"></div>
					</div>
					<div class="card-body">
						<nav>
							<div class="nav nav-tabs" id="nav-tab" role="tablist">
								<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Devices</a>
								<a class="nav-item nav-link" id="nav-statistics-tab" data-toggle="tab" href="#nav-statistics" role="tab" aria-controls="nav-profile" aria-selected="false">Statistics</a>
							</div>
						</nav>
						<div class="tab-content" id="nav-tabContent">
							<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
								<div class="row">
								{% for device in devices %}
									<div class="col-sm-12 col-md-5 col-lg-4 mt-2">
										<div class="card">
											<div class="card-header">Device Number: {{forloop.counter}}</div>
											<!-- <div class="card-body" style="white-space: pre-wrap;"> -->
												<p class="card-text ml-2">Hostname: {{device.hostname}}<br>IP Address: {{device.ip}}<br>MAC Address: {{device.mac}}</p>
											<!-- </div> -->
										</div>
									</div>
								{% endfor %}
								</div>
							</div>
							<div class="tab-pane fade" id="nav-statistics" role="tabpanel" aria-labelledby="nav-statistics-tab">
								<div class="row">
									<div class="col-12 mt-2">
										<img src="{% static 'status/img/summary1.png' %}">
									</div>
									<!-- <div class="col-12 mt-2">
										<img src="{# static 'status/img/summary2.png' #}">
									</div> -->
									<div class="col-12 mt-2">
										<img src="{% static 'status/img/summary3.png' %}">
									</div>
								</div>
							</div>
							<button type="button" onClick="window.location.reload();" class="btn btn-outline-danger mt-2" >Refresh</button>
							<!-- <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">I am here</div>
							<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">I am here</div> -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

pi-dashboard/status/templates/status/devices.html
{% extends "status/base.html" %}
{% load static %}
{% block content %}
	<p class="text-center"><strong>Dummy Data For Testing</strong></p>

	<style>
	table, th, td {
	    border: 1px solid black;
	    border-collapse: collapse;
	    padding-right: 10px;
	    padding-left: 10px;
	}
	th, td { 
	    text-align: center;
	}
	</style>
	<table style="width:100%">
	<tr>
		<th>Hostname</th>
		<th>IPv4 Address</th>
		<th>IPv6 Address</th>
		<th>MAC Address</th>
		<th>Bandwidth In</th>
		<th>Bandwidth Out</th>
		<th>Bandwidth Total</th>
		<th>Last seen</th>
	</tr>
	{% for post in posts %}
	<tr>
	    <td> {{ post.hostname }} </td>
	    <td> {{ post.ip4_address }} </td>
	    <td> {{ post.ip6_address }} </td>
	    <td> {{ post.mac_address }} </td>
	    <td> {{ post.bandw_in }} </td>
	    <td> {{ post.bandw_out }} </td>
	    <td> {{ post.bandw_total }} </td>
	    <td> {{ post.last_seen }} </td>
	</tr>
	{% endfor %}
	</table>
{% endblock content %}

pi-dashboard/status/templates/status/dhcp_dns.html
{% extends "status/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col">DHCP and DNS</div>
					</div>
					<div class="card-body">
						<nav>
							<div class="nav nav-tabs" id="nav-tab" role="tablist">
								<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Summary</a>
								<a class="nav-item nav-link" id="nav-statistics-tab" data-toggle="tab" href="#nav-statistics" role="tab" aria-controls="nav-profile" aria-selected="false">DHCP Lease</a>
							</div>
						</nav>

						<div class="tab-content" id="nav-tabContent">
							<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
								<div class="row">
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Interface</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{interface}}</div>
										</div>
									</div>
									<div class="w-100"></div>

									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Starting IP Address</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{startAddress}}</div>
										</div>
									</div>
									<div class="w-100"></div>

									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Ending IP Address</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{lastAddress}}</div>
										</div>
									</div>
									<div class="w-100"></div>

									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Lease Time</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{leaseTime}}</div>
										</div>
									</div>
									<div class="w-100"></div>

									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">DNS Server</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{dnsServer}}</div>
										</div>
									</div>
									<div class="w-100"></div>

								</div>

							</div>
							<div class="tab-pane fade" id="nav-statistics" role="tabpanel" aria-labelledby="nav-statistics-tab">
								<div class="container">
									<div class="row">
										<div class="col">Hostname</div>
										<div class="col">IP Address</div>
										<div class="col">MAC Address</div>
										<div class="col">Client ID</div>
										<div class="col">Expire Time</div>
									</div>
									{% for client in clients %}
										<!-- <div class="w-100"></div> -->
									<div class="row" style="border-top:1px solid gray;">
										<div class="col">{{client.hostname}}</div>
										<div class="col">{{client.clientIP}}</div>
										<div class="col">{{client.clientMAC}}</div>
										<div class="col">{{client.clientID}}</div>
										<div class="col">{{client.expireTime}}</div>
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

pi-dashboard/status/templates/status/hotspot.html
{% extends "status/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4">
	<div class="row">
		<div class="col-lg-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col">Hotspot</div>
					</div>
					<div class="card-body">
						<nav>
							<div class="nav nav-tabs" id="nav-tab" role="tablist">
								<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Settings</a>
							</div>
						</nav>
						<div class="tab-content" id="nav-tabContent">
							<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
								<div class="row">
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Interface</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{apInterface}}</div>
										</div>
									</div>
									<div class="w-100"></div>
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">SSID</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{apSSID}}</div>
										</div>
									</div>
									<div class="w-100"></div>
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Channel</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{apChannel}}</div>
										</div>
									</div>
									<div class="w-100"></div>
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Wireless Mode</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{apHwMode}}</div>
										</div>
									</div>
									<div class="w-100"></div>
									<div class="col-md-10 col-lg-6 mt-2">
										<div class="card">
											<div class="card-header p-2">Country Code</div>
											<div class="card-body p-1" style="white-space: pre-wrap;">{{apCountryCode}}</div>
										</div>
									</div>
								</div>
							</div>

							<script>
								function toggleHotspot() {
									let startButton = document.getElementById('startHotspot')
									let stopButton = document.getElementById('stopHotspot')
									// console.log(stopButton.style)
									// console.log(stopButton.style.display == "inline-block")
									if (stopButton.style.display == "inline-block") {
										startButton.style.display = "inline-block"
										stopButton.style.display = "none"
									} else {
										stopButton.style.display = "inline-block"
										startButton.style.display = "none"
									}

								}
							</script>
							<!-- <button style="display:inline-block" id="stopHotspot" onclick="toggleHotspot()" type="button" class="btn btn-danger mt-2">Stop Hotspot</button>
							<button style="display:none" id="startHotspot" onclick="toggleHotspot()" type="button" class="btn btn-success mt-2">Start Hotspot</button>
							<button type="button" class="btn btn-warning mt-2">Restart Hotspot</button> -->
							<!-- <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">I am here</div>
							<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">I am here</div> -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

pi-dashboard/status/templates/status/index.html
{% extends "status/base.html" %}
{% load static %}
{% block content %}
	<p class="text-center"><strong>Dummy Data For Testing</strong></p>

	<style>
	table, th, td {
	    border: 1px solid black;
	    border-collapse: collapse;
	    padding-right: 10px;
	    padding-left: 10px;
	}
	th, td { 
	    text-align: center;
	}
	</style>
	<table style="width:100%">
	<tr>
		<th>Hostname</th>
		<th>IPv4 Address</th>
		<th>IPv6 Address</th>
		<th>MAC Address</th>
		<th>Bandwidth In</th>
		<th>Bandwidth Out</th>
		<th>Bandwidth Total</th>
		<th>Last seen</th>
	</tr>
	{% for post in posts %}
	<tr>
	    <td> {{ post.hostname }} </td>
	    <td> {{ post.ip4_address }} </td>
	    <td> {{ post.ip6_address }} </td>
	    <td> {{ post.mac_address }} </td>
	    <td> {{ post.bandw_in }} </td>
	    <td> {{ post.bandw_out }} </td>
	    <td> {{ post.bandw_total }} </td>
	    <td> {{ post.last_seen }} </td>
	</tr>
	{% endfor %}

	{% for systemInfo in systemInfos %}
	<h3>{{ systemInfo.hostapStatus }}</h3>
	<h3>{{ systemInfo.cpuTemp }}</h3>
	<h3>{{ systemInfo.memFree }}</h3>
	<h3>rx Packets: {{ systemInfo.rxPackets }}</h3>
	<h3>rx Bytes: {{ systemInfo.rxBytes }}</h3>
	<h3>tx Packets: {{ systemInfo.txPackets }}</h3>
	<h3>tx Bytes: {{ systemInfo.txBytes }}</h3>
	<h3>wlan0: {{ systemInfo.nicInfo }}</h3>
	<h3>Devices: {{ systemInfo.connectedDevices }}</h3>
	{% endfor %}

	</table>
{% endblock content %}